name: CI Workflow with Discord Notification

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Fake Tests
        run: |
          echo "Running tests..."
          exit 1  # Simulate failure

  notify-on-failure:
    name: Notify Discord on Failure
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    steps:
      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\":\"🚨 GitHub Action failed in repo: ${{ github.repository }}\nWorkflow: ${{ github.workflow }}\nBranch: ${{ github.ref_name }}\n🔗 <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
